-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jun 07, 2024 at 06:46 PM
-- Server version: 8.0.30
-- PHP Version: 8.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `portal_berita`
--

-- --------------------------------------------------------

--
-- Table structure for table `berita`
--

CREATE TABLE `berita` (
  `id` int NOT NULL,
  `judul` varchar(255) NOT NULL,
  `isi` text NOT NULL,
  `author` varchar(100) NOT NULL,
  `kategori` enum('sosial','politik','ekonomi','edukasi','hiburan','olahraga','kesehatan','teknologi') CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `waktu_publikasi` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `gambar` varchar(255) DEFAULT NULL,
  `sumber` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `berita`
--

INSERT INTO `berita` (`id`, `judul`, `isi`, `author`, `kategori`, `waktu_publikasi`, `gambar`, `sumber`) VALUES
(5, ' Masyarakat Desa Kendalikan Sampah dengan Bank Sampah Digital', 'Desa Sukamaju, 7 Juni 2024 - Masyarakat Desa Sukamaju telah mengambil langkah inovatif dalam mengatasi masalah sampah dengan memperkenalkan Bank Sampah Digital. Program ini tidak hanya membantu mengurangi jumlah sampah yang menumpuk, tetapi juga meningkatkan kesadaran lingkungan di kalangan warga.\r\n\r\nBank Sampah Digital ini memungkinkan warga untuk menukarkan sampah mereka dengan poin yang dapat ditukar dengan berbagai barang kebutuhan sehari-hari. Dengan menggunakan aplikasi berbasis Android dan iOS, warga dapat mencatat dan mengelompokkan sampah mereka sebelum disetor ke pusat pengumpulan yang telah disediakan di beberapa titik strategis di desa.\r\n\r\n\"Kami melihat adanya perubahan signifikan dalam perilaku masyarakat sejak diluncurkannya program ini. Mereka lebih disiplin dalam mengelola sampah dan juga lebih peduli terhadap lingkungan sekitar,\" ujar Ibu Siti Nurjanah, Kepala Desa Sukamaju.\r\n\r\nProgram ini tidak hanya didukung oleh pemerintah desa, tetapi juga oleh beberapa perusahaan swasta yang memberikan insentif berupa barang dan voucher belanja untuk setiap poin yang terkumpul. Selain itu, Bank Sampah Digital juga bekerja sama dengan bank nasional untuk memberikan akses kredit mikro kepada warga yang aktif berpartisipasi dalam program ini.\r\n\r\nSalah satu warga, Bapak Joko Santoso, mengaku sangat terbantu dengan adanya Bank Sampah Digital. \"Selain lingkungan jadi lebih bersih, saya juga bisa mendapatkan barang-barang kebutuhan rumah tangga tanpa harus mengeluarkan uang. Ini sangat membantu ekonomi keluarga kami,\" tuturnya.\r\n\r\nProgram ini juga telah menarik perhatian berbagai pihak di luar Desa Sukamaju. Beberapa desa tetangga bahkan sudah menyatakan minat untuk mengadopsi sistem serupa di wilayah mereka. Pemerintah Kabupaten setempat menyambut baik inisiatif ini dan berencana untuk memperluas jangkauan program ke seluruh kabupaten dalam waktu dekat.\r\n\r\nHarapannya, inisiatif ini dapat menjadi contoh bagi desa-desa lain di Indonesia dalam mengelola sampah dan menjaga lingkungan, sekaligus meningkatkan kesejahteraan masyarakat melalui inovasi digital.', 'Ahmad Putra', 'sosial', '2024-06-07 06:44:56', 'uploads/sosial1.jpg', 'Harian Nusantara'),
(7, 'Pengumuman Calon Presiden: Partai Bersatu Merilis Nama-nama Calon Potensial untuk Pemilihan Presiden Mendatang', 'Partai Bersatu, salah satu partai politik terkemuka di negara ini, telah merilis daftar calon potensial yang mungkin akan diusung sebagai kandidat presiden pada pemilihan presiden mendatang. Pengumuman ini telah dinantikan oleh masyarakat sejak partai tersebut menggelar pertemuan tingkat tinggi beberapa hari yang lalu.\r\n\r\nDalam daftar yang dirilis oleh juru bicara Partai Bersatu, terdapat beberapa nama yang mencuat sebagai calon potensial yang memiliki dukungan kuat di dalam partai. Di antara nama-nama tersebut adalah Mira Wijaya, seorang politisi berpengalaman yang saat ini menjabat sebagai Menteri Keuangan, serta Arief Rahman, seorang mantan diplomat yang dikenal karena kebijakan luar negerinya yang progresif.\r\n\r\nSelain itu, terdapat juga nama-nama seperti Lestari Nurhadi, seorang aktivis hak asasi manusia yang dikenal karena advokasinya terhadap keadilan sosial, dan Rizki Pratama, seorang pengusaha sukses yang telah aktif dalam berbagai kegiatan amal dan sosial.\r\n\r\nPartai Bersatu berencana untuk mengadakan serangkaian pemilihan internal dan konsultasi dengan anggota partai serta pemimpin daerah sebelum menetapkan kandidat resmi mereka untuk pemilihan presiden. Pengumuman ini telah menimbulkan spekulasi di kalangan politisi dan masyarakat tentang kemungkinan arah politik yang akan diambil oleh Partai Bersatu dalam pemilihan presiden mendatang.', 'Rizki Pratama', 'politik', '2024-06-07 06:53:46', 'uploads/politik2.jpg', 'Tribune Politik Nasional'),
(8, 'Pemerintah Umumkan Rencana Pembangunan Jalan Tol Baru yang Melintasi Tiga Provinsi', 'Pemerintah mengumumkan rencana ambisius untuk pembangunan jalan tol baru yang akan melintasi tiga provinsi, dengan tujuan meningkatkan konektivitas dan mempercepat pertumbuhan ekonomi di wilayah tersebut.\r\n\r\nProyek ini, yang diberi nama \"Tol TransTiga,\" akan menghubungkan Provinsi A, Provinsi B, dan Provinsi C melalui jalur tol sepanjang 300 kilometer. Dalam pengumuman resminya, Menteri Pekerjaan Umum dan Perumahan Rakyat menyebut proyek ini sebagai langkah besar dalam upaya pemerintah untuk meningkatkan infrastruktur transportasi di seluruh negeri.\r\n\r\n\"Proyek Tol TransTiga akan memberikan manfaat besar bagi masyarakat dan perekonomian di tiga provinsi yang dilaluinya. Kami berkomitmen untuk mempercepat pembangunan infrastruktur yang dapat meningkatkan mobilitas dan konektivitas antar-daerah,\" kata Menteri tersebut dalam konferensi pers.\r\n\r\nRencana ini juga diharapkan dapat membuka akses baru bagi investasi dan memperluas pasar untuk produk-produk lokal. Namun, beberapa pihak mengungkapkan keprihatinan terkait dampak lingkungan dan sosial dari proyek tersebut, termasuk potensi kerusakan habitat alam dan konflik dengan masyarakat adat di sepanjang jalur proyek.\r\n\r\nPemerintah memastikan bahwa langkah-langkah akan diambil untuk memitigasi dampak negatif yang mungkin timbul dan bahwa proyek akan dilakukan dengan memperhatikan keberlanjutan lingkungan dan kesejahteraan masyarakat yang terdampak. Rencananya, konstruksi jalan tol ini akan dimulai pada tahun depan dan diharapkan selesai dalam waktu lima tahun.', 'Ahmad Ridwan', 'politik', '2024-06-07 06:57:57', 'uploads/politik1.jpg', 'Berita Politik Terkini'),
(9, 'Pasar Saham Merosot: Dampak Krisis Ekonomi Global Terhadap Investor', 'Pasar saham global mengalami penurunan tajam hari ini, mencerminkan dampak dari krisis ekonomi global yang semakin meruncing. Para investor di seluruh dunia dilanda kekhawatiran tentang prospek ekonomi masa depan, yang memicu penjualan besar-besaran aset-aset mereka.\r\n\r\nIndeks saham utama seperti Dow Jones, Nikkei, dan FTSE semuanya mengalami penurunan signifikan, menyebabkan kepanikan di pasar keuangan. Para analis mencatat bahwa ketegangan geopolitik yang terus meningkat, serta ketidakpastian seputar kebijakan ekonomi global, telah menjadi faktor utama yang memicu penurunan pasar ini.\r\n\r\nSejumlah perusahaan besar seperti teknologi, keuangan, dan energi tercatat sebagai salah satu yang paling terdampak oleh penurunan ini. Saham-saham perusahaan tersebut mengalami penurunan harga yang signifikan, memicu kekhawatiran di kalangan investor tentang stabilitas pasar jangka panjang.\r\n\r\nPara ahli ekonomi memperingatkan bahwa kondisi ini dapat memicu spiral negatif yang lebih dalam jika tidak ditangani dengan cepat dan efektif. Pemerintah di berbagai negara telah dihadapkan pada tekanan untuk mengambil langkah-langkah konkret guna meredam dampak dari krisis ekonomi global ini, termasuk stimulus ekonomi dan kebijakan moneter yang lebih longgar.\r\n\r\nSementara itu, investor di seluruh dunia diharapkan untuk tetap waspada dan mengambil langkah-langkah yang bijaksana untuk melindungi portofolio investasi mereka dari gejolak pasar yang belum menentu ini.', 'Dian Pratiwi', 'ekonomi', '2024-06-07 07:00:36', 'uploads/ekonomi1.jpg', 'Ekonomi Harian'),
(10, 'Revitalisasi Ekonomi: Pemerintah Luncurkan Program Stimulus Besar-besaran untuk Dorong Pertumbuhan Usaha Kecil Menengah', 'Dalam upaya untuk mengatasi dampak ekonomi yang ditimbulkan oleh pandemi dan mempercepat pemulihan ekonomi nasional, pemerintah telah meluncurkan program stimulus besar-besaran yang ditujukan untuk mendukung pertumbuhan usaha kecil menengah (UKM) di seluruh negeri.\r\n\r\nProgram ini mencakup sejumlah insentif ekonomi yang dirancang untuk merangsang investasi dan pertumbuhan UKM, termasuk pembebasan pajak, bantuan modal, serta bantuan teknis dan pelatihan bagi para pengusaha UKM. Selain itu, pemerintah juga akan mengalokasikan dana tambahan untuk memperkuat infrastruktur ekonomi lokal, termasuk transportasi dan komunikasi.\r\n\r\nMenurut Menteri Keuangan, program ini bertujuan untuk memberikan dorongan yang diperlukan bagi sektor UKM, yang merupakan tulang punggung ekonomi nasional dan pendorong utama lapangan kerja. \"Kami percaya bahwa dengan memberikan dukungan yang tepat kepada UKM, kami dapat mempercepat pemulihan ekonomi dan menciptakan peluang baru bagi pertumbuhan jangka panjang,\" ujarnya dalam konferensi pers yang diselenggarakan untuk mengumumkan program ini.\r\n\r\nPara analis ekonomi menyambut baik langkah-langkah ini, mengatakan bahwa program stimulus yang terfokus pada UKM adalah langkah yang tepat untuk merangsang aktivitas ekonomi di tingkat lokal dan regional. Diharapkan bahwa implementasi program ini akan membantu mengatasi tantangan ekonomi yang dihadapi oleh UKM dan mempercepat pemulihan ekonomi nasional secara keseluruhan.', 'Indra Cahyadi', 'ekonomi', '2024-06-07 07:02:23', 'uploads/ekonomi2.jpg', 'Bisnis Ekonomi Hari Ini'),
(11, 'Inovasi Pendidikan: Sekolah XYZ Mengadopsi Metode Pembelajaran Berbasis Game untuk Tingkatkan Minat Belajar Siswa', 'Sekolah XYZ, sebuah sekolah menengah di kota metropolitan, telah mengadopsi metode pembelajaran berbasis game yang inovatif untuk meningkatkan minat belajar dan keterlibatan siswa dalam proses pembelajaran. Metode ini merupakan bagian dari upaya sekolah untuk terus memperbarui pendekatan mereka terhadap pengajaran dan pembelajaran.\r\n\r\nDalam metode ini, materi pelajaran disajikan melalui permainan komputer yang dirancang khusus untuk menciptakan pengalaman belajar yang interaktif dan menyenangkan. Para siswa diundang untuk berpartisipasi dalam berbagai tantangan, misi, dan simulasi yang dirancang untuk menguji pemahaman mereka tentang materi pelajaran dan mendorong kreativitas serta pemecahan masalah.\r\n\r\nMenurut Kepala Sekolah XYZ, metode pembelajaran berbasis game ini telah membawa perubahan positif dalam kelas. \"Kami melihat peningkatan yang signifikan dalam minat belajar siswa sejak menerapkan pendekatan ini. Mereka lebih antusias dan bersemangat untuk belajar, karena mereka merasa terlibat secara aktif dalam proses pembelajaran,\" ungkapnya.\r\n\r\nReaksi positif juga datang dari para orang tua, yang melaporkan bahwa anak-anak mereka lebih termotivasi dan bersemangat tentang sekolah sejak penggunaan metode ini. Beberapa di antara mereka bahkan melaporkan bahwa anak-anak mereka menjadi lebih mandiri dalam belajar dan lebih percaya diri dalam mengeksplorasi konsep-konsep baru.\r\n\r\nMetode pembelajaran berbasis game ini diharapkan akan terus berkembang dan digunakan oleh lebih banyak sekolah di masa depan, sebagai bagian dari upaya untuk menciptakan lingkungan pembelajaran yang menarik dan efektif bagi generasi siswa yang semakin digital.', 'Dian Pratiwi', 'edukasi', '2024-06-07 07:05:13', 'uploads/edukasi1.jpg', ' Edukasi Plus'),
(12, 'Inovasi Pembelajaran: Sekolah di Kota Y Integrasikan Pembelajaran Berbasis Kecerdasan Buatan untuk Meningkatkan Prestasi Siswa', 'Sekolah di Kota Y telah mengambil langkah besar dalam memperbarui pendidikan dengan mengintegrasikan teknologi kecerdasan buatan (AI) ke dalam proses pembelajaran mereka. Langkah ini diambil sebagai bagian dari upaya untuk meningkatkan kualitas pendidikan dan prestasi siswa di sekolah-sekolah di wilayah tersebut.\r\n\r\nDalam program ini, AI digunakan untuk menganalisis data pembelajaran siswa, mengidentifikasi kebutuhan individu mereka, dan menyediakan rekomendasi untuk pendekatan pembelajaran yang lebih efektif. Selain itu, teknologi AI juga digunakan untuk menciptakan pengalaman pembelajaran yang lebih interaktif dan menarik bagi siswa, melalui aplikasi mobile dan platform e-learning yang dikembangkan khusus.\r\n\r\nMenurut Kepala Sekolah, langkah ini bertujuan untuk memberikan pendidikan yang lebih personal dan disesuaikan untuk setiap siswa, serta untuk membantu meningkatkan keterlibatan mereka dalam proses pembelajaran. \"Dengan memanfaatkan kecerdasan buatan, kami berharap dapat menciptakan lingkungan belajar yang lebih adaptif dan responsif, sehingga setiap siswa dapat mencapai potensi mereka yang penuh,\" katanya.\r\n\r\nReaksi terhadap integrasi teknologi AI dalam pendidikan ini cukup positif, dengan banyak orang tua dan guru mengapresiasi upaya sekolah untuk memanfaatkan inovasi teknologi dalam meningkatkan kualitas pendidikan. Diharapkan bahwa langkah ini akan menjadi contoh bagi sekolah-sekolah lain di seluruh negeri untuk mengadopsi pendekatan pembelajaran yang lebih inovatif dan efektif.', 'Nia Cahaya', 'edukasi', '2024-06-07 07:08:59', 'uploads/edukasi2.jpg', 'Edukasi Maju'),
(13, 'Tim Sepak Bola Nasional Raih Kemenangan Dramatis di Babak Penyisihan Piala Dunia 2024', 'Tim sepak bola nasional kita menorehkan kemenangan dramatis dalam pertandingan yang sangat diantisipasi di babak penyisihan Piala Dunia 2024. Dalam pertandingan yang berlangsung di Stadion Utama Kota X, tim berhasil mengalahkan lawan tangguhnya dengan skor 3-2 dalam pertandingan yang penuh gairah.\r\n\r\nPertandingan yang ketat dan seru ini menyaksikan kedua tim saling bertukar serangan sepanjang pertandingan. Gol-gol yang dicetak oleh pemain terbaik dari kedua tim membuat penonton terus tertegun dan terlibat dalam suasana yang penuh semangat.\r\n\r\nKemenangan ini membawa tim kita ke posisi terdepan dalam klasemen sementara babak penyisihan, dengan harapan untuk melangkah lebih jauh di turnamen bergengsi ini. Pelatih tim nasional, Budi Santoso, menggambarkan kemenangan ini sebagai langkah penting menuju pencapaian tujuan tim.\r\n\r\n\"Kemenangan ini adalah hasil dari kerja keras dan dedikasi seluruh tim. Kami akan terus bekerja keras dan fokus untuk mencapai prestasi yang lebih besar di Piala Dunia ini,\" ujar Budi Santoso dalam konferensi pers setelah pertandingan.\r\n\r\nKemenangan ini juga membangkitkan semangat para penggemar sepak bola di seluruh negeri, yang telah memberikan dukungan tak tergoyahkan bagi tim nasional. Dengan performa yang mengesankan ini, harapan untuk membawa pulang trofi Piala Dunia semakin terasa nyata bagi para penggemar sepak bola Indonesia.', 'Ahmad Rizky', 'olahraga', '2024-06-07 07:10:41', 'uploads/olahraga1.jpg', 'Olahraga Terkini'),
(14, 'Tim Sepak Bola Nasional Membawa Pulang Emas di Piala Dunia 2024: Kemenangan Gemilang di Final Melawan Tim Spanyol', 'Tim Sepak Bola Nasional kita meraih kemenangan gemilang setelah mengalahkan tim Spanyol dalam pertandingan final Piala Dunia 2024 yang digelar di Stadion Maracanã, Rio de Janeiro. Pertandingan final yang sengit dan penuh gairah itu berakhir dengan skor akhir 3-2 untuk keunggulan tim kita.\r\n\r\nDalam pertandingan yang dipenuhi tensi tersebut, kedua tim saling beradu kemampuan dan menunjukkan performa terbaik mereka. Namun, tim kita berhasil unggul lebih dulu melalui gol yang dicetak oleh striker terbaik kita, Ridwan \"The Lightning\" Ibrahim, pada menit ke-25. Namun, Spanyol tidak menyerah begitu saja dan berhasil menyamakan kedudukan melalui gol dari pemain andalannya, Diego Martinez, sebelum babak pertama berakhir.\r\n\r\nBabak kedua berlangsung dengan tempo yang lebih tinggi, namun kita berhasil mencetak gol kedua melalui tendangan bebas yang brilian dari kapten tim, Ahmad \"The Magician\" Susanto, pada menit ke-65. Meskipun Spanyol berhasil menyamakan kedudukan sekali lagi melalui gol Martinez pada menit ke-80, kita tidak menyerah dan terus menekan pertahanan lawan.\r\n\r\nPada menit ke-88, Ridwan Ibrahim mencetak gol kemenangan untuk tim kita setelah menerima umpan silang yang brilian dari gelandang sayap, Budi \"The Flash\" Santoso. Gol tersebut memicu sorakan meriah dari para pendukung yang memenuhi stadion. Kemenangan ini mengantar kita meraih gelar juara Piala Dunia untuk kali kedua dalam sejarah sepak bola nasional kita, setelah sebelumnya meraihnya pada tahun 1998.\r\n\r\nPelatih tim kita, Bambang \"The Mastermind\" Santoso, menyatakan rasa bangga atas pencapaian timnya. \"Ini adalah momen bersejarah bagi sepak bola nasional kita. Para pemain telah memberikan yang terbaik dari diri mereka dan layak mendapatkan penghargaan ini,\" ujarnya dengan penuh emosi.\r\n\r\nKemenangan ini juga menjadi sumber inspirasi bagi generasi muda untuk mengejar mimpi mereka dan membuktikan bahwa dengan kerja keras dan dedikasi, segala hal adalah mungkin.', 'Dian Pratama', 'olahraga', '2024-06-07 07:12:46', 'uploads/olahraga2.jpg', 'Sports Today'),
(15, 'Peluncuran Film Terbaru \'Harmoni Cinta\' Meriahkan Karpet Merah di Festival Film Internasional', 'Pekan ini, Karpet Merah Festival Film Internasional menjadi sorotan dunia saat para bintang film papan atas berkumpul untuk merayakan peluncuran film terbaru yang sangat dinanti-nantikan, \"Harmoni Cinta\". Acara yang diadakan di Gedung Teater Metropolitan ini menghadirkan kegemilangan dan sorotan yang luar biasa.\r\n\r\n\"Harmoni Cinta\" merupakan karya sutradara terkenal, Anton Widjaya, yang menggambarkan kisah cinta yang penuh warna dan mendalam di tengah-tengah lanskap urban yang modern. Film ini menampilkan akting memukau dari para bintang ternama, seperti Rizky Pratama dan Amanda Putri, yang membawa penonton dalam perjalanan emosional yang tak terlupakan.\r\n\r\nPada malam peluncuran, para selebriti dan pembuat film berjajar di Karpet Merah dalam busana mewah yang memukau, menyambut para fotografer dan wartawan yang ingin menangkap momen-momen bersejarah. Suasana penuh semangat dan antusiasme terasa di udara, mengisyaratkan keberhasilan besar yang akan datang bagi film ini.\r\n\r\n\"Kami sangat bangga dan senang bisa menjadi bagian dari proyek film ini. Semua orang di belakang layar telah bekerja keras untuk menciptakan sesuatu yang istimewa, dan kami berharap film ini akan menyentuh hati penonton di seluruh dunia,\" ujar Rizky Pratama, salah satu bintang utama \"Harmoni Cinta\".\r\n\r\nDengan sorotan yang luar biasa di Festival Film Internasional ini, \"Harmoni Cinta\" diprediksi akan menjadi salah satu film terlaris tahun ini dan memberikan kontribusi besar bagi industri perfilman Indonesia.', 'Maya Sari', 'hiburan', '2024-06-07 07:15:30', 'uploads/hiburan1.jpg', 'Gaya Hiburan'),
(16, 'Penyanyi Terkenal Arief Rahman Mengumumkan Tur Konser Dunia untuk Mendukung Pendidikan Anak-anak Miskin', 'Penyanyi terkenal dan aktivis sosial, Arief Rahman, telah mengumumkan rencana untuk melakukan tur konser dunia yang bertujuan untuk mendukung pendidikan anak-anak miskin di berbagai belahan dunia. Tur konser yang dijadwalkan akan dimulai bulan depan ini akan mencakup sejumlah kota besar di Asia, Eropa, dan Amerika.\r\n\r\nDalam konferensi pers yang diadakan di Jakarta, Arief Rahman menjelaskan bahwa semua pendapatan dari konser-konser tersebut akan disumbangkan untuk mendukung pembangunan sekolah dan program pendidikan bagi anak-anak yang kurang mampu di negara-negara yang terpilih.\r\n\r\n\"Aku merasa beruntung bisa menggunakan bakat musikku untuk tujuan yang lebih besar, yaitu membantu anak-anak yang kurang beruntung mendapatkan akses pendidikan yang layak,\" kata Arief Rahman.\r\n\r\nTur konser ini mendapat sambutan hangat dari penggemar Arief Rahman dan komunitas internasional yang peduli terhadap pendidikan. Banyak yang menyanjung keputusan penyanyi tersebut untuk menggunakan pengaruh dan popularitasnya demi tujuan yang mulia.\r\n\r\nSelain menghibur para penggemar dengan lagu-lagu hitsnya, Arief Rahman juga berencana untuk menyampaikan pesan tentang pentingnya memberikan kesempatan pendidikan kepada setiap anak, tidak peduli latar belakang ekonomi atau sosial mereka.\r\n\r\nDengan tur konser ini, diharapkan akan tercipta kesadaran yang lebih besar tentang masalah pendidikan global dan bahwa setiap individu, termasuk selebriti, memiliki peran untuk membawa perubahan positif dalam masyarakat.', 'Rizka Maulida', 'hiburan', '2024-06-07 07:18:05', 'uploads/hiburan2.jpg', 'Gaya Hidup Artis'),
(17, 'Studi Baru Temukan Hubungan Positif Antara Aktivitas Fisik dan Kesehatan Mental', 'Sebuah studi baru yang dipublikasikan dalam jurnal kedokteran terkemuka menemukan hubungan positif yang signifikan antara aktivitas fisik dan kesehatan mental. Penelitian ini dilakukan oleh tim ahli kesehatan dari beberapa universitas ternama di seluruh dunia.\r\n\r\nMelalui survei yang melibatkan ribuan partisipan dari berbagai kelompok usia dan latar belakang, para peneliti menemukan bahwa individu yang melakukan aktivitas fisik secara teratur cenderung memiliki tingkat kesehatan mental yang lebih baik. Aktivitas fisik seperti berjalan kaki, berlari, bersepeda, dan olahraga lainnya dikaitkan dengan peningkatan mood positif, penurunan tingkat stres, dan peningkatan kesejahteraan secara keseluruhan.\r\n\r\nDr. Ahmad, salah satu peneliti utama dalam studi ini, menjelaskan bahwa aktivitas fisik dapat merangsang pelepasan endorfin dan neurotransmiter lainnya yang dapat meningkatkan suasana hati dan mengurangi gejala stres dan kecemasan. \"Hasil studi ini memberikan bukti tambahan tentang pentingnya memasukkan aktivitas fisik ke dalam gaya hidup sehari-hari untuk menjaga kesehatan mental kita,\" ujarnya.\r\n\r\nTemuan ini memberikan dorongan tambahan bagi masyarakat untuk mengadopsi gaya hidup yang aktif dan sehat, tidak hanya untuk meningkatkan kesehatan fisik tetapi juga untuk mendukung kesehatan mental yang baik. Dengan memahami hubungan yang kuat antara aktivitas fisik dan kesehatan mental, diharapkan akan lebih banyak orang yang termotivasi untuk menjaga kebugaran fisik mereka dan merawat kesehatan mental mereka dengan lebih baik.', 'Fitriani Santoso', 'kesehatan', '2024-06-07 07:19:10', 'uploads/kesehatan1.jpg', 'Kesehatan & Kondisi Tubuh'),
(18, 'Studi Terbaru Ungkap Manfaat Luar Biasa Olahraga Teratur terhadap Kesehatan Mental', 'Studi terbaru yang dilakukan oleh para peneliti di Universitas Nasional menunjukkan bahwa olahraga teratur memiliki manfaat yang luar biasa terhadap kesehatan mental seseorang. Dalam penelitian yang melibatkan ribuan partisipan dari berbagai kelompok usia, ditemukan bahwa aktivitas fisik yang konsisten dapat membantu mengurangi risiko gangguan mental seperti depresi dan kecemasan.\r\n\r\nMenurut Dr. Andika Wijaya, salah seorang peneliti yang terlibat dalam studi tersebut, aktivitas fisik meningkatkan produksi endorfin dalam tubuh, zat kimia alami yang dapat meningkatkan mood dan mengurangi stres. Selain itu, olahraga juga dapat meningkatkan rasa percaya diri dan memperbaiki tidur, yang keduanya berperan penting dalam menjaga kesehatan mental.\r\n\r\n\"Hasil studi kami menegaskan pentingnya olahraga dalam menjaga kesehatan mental. Bahkan aktivitas fisik ringan seperti berjalan kaki atau bersepeda dapat memberikan manfaat yang signifikan,\" jelas Dr. Andika.\r\n\r\nPara ahli kesehatan mendorong masyarakat untuk memasukkan olahraga ke dalam gaya hidup sehari-hari sebagai bagian dari upaya untuk menjaga kesehatan mental. Mereka juga menekankan pentingnya memilih jenis olahraga yang sesuai dengan preferensi dan kebutuhan individu untuk memastikan konsistensi dan keberlanjutan dalam aktivitas fisik.\r\n\r\nDengan penekanan yang semakin besar pada kesehatan mental dalam masyarakat saat ini, hasil studi ini diharapkan dapat memberikan dorongan tambahan bagi individu untuk memprioritaskan olahraga dalam upaya menjaga kesejahteraan mental mereka.', 'Fitriani Nurul', 'kesehatan', '2024-06-07 07:20:37', 'uploads/kesehatan2.jpg', 'Kesehatan & Kebugaran'),
(19, 'Aplikasi Kesehatan Terbaru \'SehatPlus\' Menghadirkan Fitur Inovatif untuk Monitoring Kesehatan Secara Real-Time', 'Dalam era di mana teknologi semakin mempengaruhi berbagai aspek kehidupan, kesehatan juga tidak luput dari perkembangan teknologi yang pesat. Baru-baru ini, diluncurkan sebuah aplikasi kesehatan terbaru bernama \'SehatPlus\' yang menjanjikan fitur inovatif untuk monitoring kesehatan secara real-time.\r\n\r\nAplikasi ini dikembangkan oleh tim ahli teknologi dan dokter spesialis kesehatan dengan tujuan untuk memberikan akses mudah dan cepat bagi pengguna untuk memantau kondisi kesehatan mereka secara langsung melalui perangkat mobile mereka. Fitur utama \'SehatPlus\' adalah kemampuannya untuk mengintegrasikan data dari berbagai perangkat wearable, seperti smartwatch dan sensor kesehatan lainnya, sehingga pengguna dapat melacak informasi vital seperti detak jantung, tingkat aktivitas, dan kualitas tidur mereka secara real-time.\r\n\r\n\"Kami percaya bahwa dengan memanfaatkan teknologi wearable dan aplikasi mobile, kita dapat memberikan kemudahan bagi individu untuk mengelola dan memantau kesehatan mereka dengan lebih efektif. \'SehatPlus\' dirancang untuk menjadi asisten kesehatan pribadi yang dapat diandalkan,\" ungkap Dr. Faisal, salah seorang anggota tim pengembang aplikasi.\r\n\r\nSelain fitur pemantauan kesehatan real-time, \'SehatPlus\' juga menyediakan berbagai fitur lain seperti jadwal pengingat obat, catatan kesehatan pribadi, dan konsultasi online dengan dokter spesialis. Aplikasi ini diharapkan dapat menjadi alat yang berguna bagi individu untuk menjaga kesehatan mereka dengan lebih proaktif dan terorganisir.\r\n\r\nDalam uji coba awal, \'SehatPlus\' telah menerima tanggapan positif dari pengguna yang mengapresiasi kemudahan penggunaan dan keakuratan informasi yang disediakan oleh aplikasi ini. Dengan perkembangan teknologi kesehatan yang semakin maju, diharapkan aplikasi seperti \'SehatPlus\' dapat membantu memperbaiki akses dan pengelolaan kesehatan secara global.', 'Pratiwi Dian', 'teknologi', '2024-06-07 07:23:00', 'uploads/teknologi1.jpg', 'Teknologi Kesehatan Terkini'),
(20, 'Perusahaan Teknologi Terkemuka Rilis Perangkat Lunak Kecerdasan Buatan Terbaru untuk Meningkatkan Efisiensi Bisnis', 'Perusahaan teknologi terkemuka, InnovateTech, telah merilis perangkat lunak kecerdasan buatan terbaru mereka yang dirancang untuk meningkatkan efisiensi operasional dan produktivitas bisnis. Perangkat lunak yang diberi nama \"AI Solutions 5.0\" ini menjanjikan berbagai fitur canggih yang akan membantu perusahaan dalam menganalisis data, mengoptimalkan proses bisnis, dan mengambil keputusan secara lebih cerdas.\r\n\r\nDalam keterangan resminya, CEO InnovateTech, Amanda Putri, menjelaskan bahwa AI Solutions 5.0 memiliki kemampuan untuk belajar dari data secara mandiri dan mengidentifikasi pola-pola yang dapat membantu perusahaan dalam membuat keputusan yang lebih baik dan lebih cepat. \"Kami percaya bahwa dengan memanfaatkan kecerdasan buatan, perusahaan dapat menghadapi tantangan bisnis dengan lebih baik dan mencapai hasil yang lebih optimal,\" ujarnya.\r\n\r\nBeberapa fitur unggulan dari AI Solutions 5.0 termasuk analisis prediktif yang dapat membantu perusahaan dalam meramalkan tren pasar, deteksi anomali yang membantu mengidentifikasi potensi masalah dalam operasi bisnis, dan otomatisasi proses yang dapat mengurangi waktu dan biaya operasional.\r\n\r\nReaksi terhadap peluncuran perangkat lunak ini cukup positif, dengan banyak perusahaan yang menyambut baik inovasi baru ini dan berencana untuk mengimplementasikannya dalam operasi bisnis mereka. Diharapkan bahwa AI Solutions 5.0 akan membuka jalan bagi transformasi digital yang lebih luas di berbagai sektor industri dan membantu perusahaan dalam menghadapi persaingan bisnis yang semakin ketat di era digital ini.', 'Aditya Pratama', 'teknologi', '2024-06-07 07:24:11', 'uploads/teknologi2.jpg', 'Teknologi Maju'),
(21, 'Perusahaan Teknologi Terkemuka Umumkan Peluncuran Smartphone Revolusioner dengan Teknologi Kamera Baru', 'Perusahaan teknologi terkemuka, XYZ Corp, mengumumkan peluncuran smartphone terbarunya yang dijanjikan akan mengubah paradigma fotografi mobile. Smartphone baru ini, yang diberi nama \"XYZ Vision X\", dilengkapi dengan teknologi kamera revolusioner yang menawarkan pengalaman fotografi yang belum pernah terjadi sebelumnya di industri smartphone.\r\n\r\nSalah satu fitur unggulan dari smartphone ini adalah teknologi kamera AI SuperVision yang dapat mengenali dan mengoptimalkan pengaturan kamera secara otomatis sesuai dengan lingkungan dan subjek yang difoto. Ini memungkinkan pengguna untuk mengambil foto-foto berkualitas profesional tanpa harus menguasai pengaturan manual kamera.\r\n\r\nSelain itu, XYZ Vision X juga dilengkapi dengan mode SuperZoom yang memungkinkan pengguna untuk melakukan zoom hingga 10x tanpa mengorbankan kualitas gambar. Ini menjadi terobosan besar dalam industri smartphone, memungkinkan pengguna untuk mendapatkan detail yang lebih jelas bahkan dari jarak jauh.\r\n\r\nDalam konferensi pers yang diadakan untuk memperkenalkan smartphone baru ini, CEO XYZ Corp, Michelle Tan, menyatakan, \"XYZ Vision X adalah perwujudan visi kami untuk memberikan teknologi terdepan kepada pengguna kami. Dengan teknologi kamera terbaru ini, kami berharap dapat memberikan pengalaman fotografi yang tak tertandingi kepada para pengguna kami.\"\r\n\r\nReaksi awal terhadap pengumuman ini sangat positif, dengan para pengamat teknologi dan konsumen smartphone menyambut hangat inovasi ini. Banyak yang menyatakan antusiasme mereka untuk mencoba fitur-fitur baru smartphone ini dan melihat bagaimana teknologi kamera ini dapat mengubah cara mereka berfotografi dengan smartphone.', 'Aditya Putra', 'teknologi', '2024-06-07 07:25:05', 'uploads/teknologi3.jpg', 'Teknologi Update'),
(40, 'Inovasi Sosial: Kelompok Remaja di Desa X Menciptakan Program Pendidikan Alternatif bagi Anak Jalanan', 'Sebuah kelompok remaja di Desa X telah menciptakan program pendidikan alternatif yang inovatif untuk membantu anak-anak jalanan setempat. Program ini bertujuan untuk memberikan akses pendidikan kepada anak-anak yang tidak memiliki akses atau terpinggirkan dari sistem pendidikan formal.\r\n\r\nDiketuai oleh Andika, seorang remaja berusia 18 tahun yang gigih, kelompok ini telah bekerja sama dengan para penduduk setempat, guru, dan beberapa sukarelawan untuk mengembangkan program tersebut. Program ini mencakup pelajaran dasar seperti membaca, menulis, dan matematika, serta keterampilan praktis seperti pertanian perkotaan dan kerajinan tangan.\r\n\r\nMenurut Andika, ide untuk program ini muncul ketika ia melihat sejumlah anak jalanan di desanya bermain di jalanan tanpa akses pendidikan yang layak. \"Saya percaya bahwa setiap anak berhak mendapatkan pendidikan. Dengan program ini, kami berusaha untuk memberikan kesempatan yang sama kepada anak-anak jalanan untuk belajar dan berkembang,\" ujarnya.\r\nProgram pendidikan alternatif ini telah mendapatkan sambutan hangat dari masyarakat setempat dan telah berhasil menarik minat sejumlah anak jalanan untuk bergabung. Diharapkan bahwa program ini dapat menjadi contoh bagi desa-desa lain dalam memberikan solusi terhadap masalah sosial di lingkungan mereka', 'Amanda Putri', 'sosial', '2024-06-07 18:23:05', 'uploads/sosial2.jpg', 'Harian Masyarakat Sejahtera');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int NOT NULL,
  `email` varchar(255) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `email`, `username`, `password`) VALUES
(1, '', 'c', '$2y$10$T3hMOv6KG3GlU9Np3HEuEuEJGrfAud.48h0FmbP9naqnnOnYfvbjS'),
(9, 'aliamaelani@gmail.com', 'alia maelani', '$2y$10$lUTodyW2b7MAGqw4TWjF/OdxUfwqzYij0xj7QtLoTkX11yVa.bHpS'),
(15, 'user@gmail.com', 'user', '$2y$10$t59bDwo2quTvP1UAgueGGej/OaFWVd4L3.A/L2MBuaZsXw4KZ0saK');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `berita`
--
ALTER TABLE `berita`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `berita`
--
ALTER TABLE `berita`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
